FROM node:alpine as builder

WORKDIR /app

COPY . ./

RUN npm install --silent

RUN npm run build

FROM node:alpine

COPY --from=builder /app/build ./build

RUN npm install -g serve

EXPOSE 5000

CMD ["serve", "-p", "5000", "-s", "./build"]