// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.17.1
// source: messagehub.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageHubCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner                string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Subdomain            string `protobuf:"bytes,2,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	Notes                string `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	HubType              string `protobuf:"bytes,4,opt,name=hub_type,json=hubType,proto3" json:"hub_type,omitempty"`
	TransactionReference string `protobuf:"bytes,5,opt,name=transaction_reference,json=transactionReference,proto3" json:"transaction_reference,omitempty"`
}

func (x *MessageHubCreateRequest) Reset() {
	*x = MessageHubCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubCreateRequest) ProtoMessage() {}

func (x *MessageHubCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubCreateRequest.ProtoReflect.Descriptor instead.
func (*MessageHubCreateRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHubCreateRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MessageHubCreateRequest) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *MessageHubCreateRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *MessageHubCreateRequest) GetHubType() string {
	if x != nil {
		return x.HubType
	}
	return ""
}

func (x *MessageHubCreateRequest) GetTransactionReference() string {
	if x != nil {
		return x.TransactionReference
	}
	return ""
}

type MessageHubRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address           string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Details           string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	PostLimit         int32  `protobuf:"varint,3,opt,name=post_limit,json=postLimit,proto3" json:"post_limit,omitempty"`
	AllowFriendGroups bool   `protobuf:"varint,4,opt,name=allow_friend_groups,json=allowFriendGroups,proto3" json:"allow_friend_groups,omitempty"`
}

func (x *MessageHubRegisterRequest) Reset() {
	*x = MessageHubRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubRegisterRequest) ProtoMessage() {}

func (x *MessageHubRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubRegisterRequest.ProtoReflect.Descriptor instead.
func (*MessageHubRegisterRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{1}
}

func (x *MessageHubRegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MessageHubRegisterRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *MessageHubRegisterRequest) GetPostLimit() int32 {
	if x != nil {
		return x.PostLimit
	}
	return 0
}

func (x *MessageHubRegisterRequest) GetAllowFriendGroups() bool {
	if x != nil {
		return x.AllowFriendGroups
	}
	return false
}

type MessageHubHubsResponseHub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address           string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	User              *User  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	CreatedAt         string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ApprovedAt        string `protobuf:"bytes,5,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	DisabledAt        string `protobuf:"bytes,6,opt,name=disabled_at,json=disabledAt,proto3" json:"disabled_at,omitempty"`
	Details           string `protobuf:"bytes,7,opt,name=details,proto3" json:"details,omitempty"`
	PostLimit         int32  `protobuf:"varint,8,opt,name=post_limit,json=postLimit,proto3" json:"post_limit,omitempty"`
	AllowFriendGroups bool   `protobuf:"varint,9,opt,name=allow_friend_groups,json=allowFriendGroups,proto3" json:"allow_friend_groups,omitempty"`
	ExpirationDays    int32  `protobuf:"varint,10,opt,name=expiration_days,json=expirationDays,proto3" json:"expiration_days,omitempty"`
}

func (x *MessageHubHubsResponseHub) Reset() {
	*x = MessageHubHubsResponseHub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubHubsResponseHub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubHubsResponseHub) ProtoMessage() {}

func (x *MessageHubHubsResponseHub) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubHubsResponseHub.ProtoReflect.Descriptor instead.
func (*MessageHubHubsResponseHub) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{2}
}

func (x *MessageHubHubsResponseHub) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageHubHubsResponseHub) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MessageHubHubsResponseHub) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *MessageHubHubsResponseHub) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MessageHubHubsResponseHub) GetApprovedAt() string {
	if x != nil {
		return x.ApprovedAt
	}
	return ""
}

func (x *MessageHubHubsResponseHub) GetDisabledAt() string {
	if x != nil {
		return x.DisabledAt
	}
	return ""
}

func (x *MessageHubHubsResponseHub) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *MessageHubHubsResponseHub) GetPostLimit() int32 {
	if x != nil {
		return x.PostLimit
	}
	return 0
}

func (x *MessageHubHubsResponseHub) GetAllowFriendGroups() bool {
	if x != nil {
		return x.AllowFriendGroups
	}
	return false
}

func (x *MessageHubHubsResponseHub) GetExpirationDays() int32 {
	if x != nil {
		return x.ExpirationDays
	}
	return 0
}

type MessageHubHubsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hubs []*MessageHubHubsResponseHub `protobuf:"bytes,1,rep,name=hubs,proto3" json:"hubs,omitempty"`
}

func (x *MessageHubHubsResponse) Reset() {
	*x = MessageHubHubsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubHubsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubHubsResponse) ProtoMessage() {}

func (x *MessageHubHubsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubHubsResponse.ProtoReflect.Descriptor instead.
func (*MessageHubHubsResponse) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{3}
}

func (x *MessageHubHubsResponse) GetHubs() []*MessageHubHubsResponseHub {
	if x != nil {
		return x.Hubs
	}
	return nil
}

type MessageHubVerifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubId string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
}

func (x *MessageHubVerifyRequest) Reset() {
	*x = MessageHubVerifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubVerifyRequest) ProtoMessage() {}

func (x *MessageHubVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubVerifyRequest.ProtoReflect.Descriptor instead.
func (*MessageHubVerifyRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{4}
}

func (x *MessageHubVerifyRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

type MessageHubVerifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MessageHubVerifyResponse) Reset() {
	*x = MessageHubVerifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubVerifyResponse) ProtoMessage() {}

func (x *MessageHubVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubVerifyResponse.ProtoReflect.Descriptor instead.
func (*MessageHubVerifyResponse) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{5}
}

func (x *MessageHubVerifyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MessageHubApproveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubId string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
}

func (x *MessageHubApproveRequest) Reset() {
	*x = MessageHubApproveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubApproveRequest) ProtoMessage() {}

func (x *MessageHubApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubApproveRequest.ProtoReflect.Descriptor instead.
func (*MessageHubApproveRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{6}
}

func (x *MessageHubApproveRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

type MessageHubApproveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MessageHubApproveResponse) Reset() {
	*x = MessageHubApproveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubApproveResponse) ProtoMessage() {}

func (x *MessageHubApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubApproveResponse.ProtoReflect.Descriptor instead.
func (*MessageHubApproveResponse) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{7}
}

func (x *MessageHubApproveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MessageHubRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubId     string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	Subdomain string `protobuf:"bytes,2,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
}

func (x *MessageHubRemoveRequest) Reset() {
	*x = MessageHubRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubRemoveRequest) ProtoMessage() {}

func (x *MessageHubRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubRemoveRequest.ProtoReflect.Descriptor instead.
func (*MessageHubRemoveRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{8}
}

func (x *MessageHubRemoveRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *MessageHubRemoveRequest) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

type MessageHubRemoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []string `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *MessageHubRemoveResponse) Reset() {
	*x = MessageHubRemoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubRemoveResponse) ProtoMessage() {}

func (x *MessageHubRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubRemoveResponse.ProtoReflect.Descriptor instead.
func (*MessageHubRemoveResponse) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{9}
}

func (x *MessageHubRemoveResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MessageHubSetPostLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubId     string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	PostLimit int32  `protobuf:"varint,2,opt,name=post_limit,json=postLimit,proto3" json:"post_limit,omitempty"`
}

func (x *MessageHubSetPostLimitRequest) Reset() {
	*x = MessageHubSetPostLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubSetPostLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubSetPostLimitRequest) ProtoMessage() {}

func (x *MessageHubSetPostLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubSetPostLimitRequest.ProtoReflect.Descriptor instead.
func (*MessageHubSetPostLimitRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{10}
}

func (x *MessageHubSetPostLimitRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *MessageHubSetPostLimitRequest) GetPostLimit() int32 {
	if x != nil {
		return x.PostLimit
	}
	return 0
}

type MessageHubSetAllowFriendGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubId             string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	AllowFriendGroups bool   `protobuf:"varint,2,opt,name=allow_friend_groups,json=allowFriendGroups,proto3" json:"allow_friend_groups,omitempty"`
}

func (x *MessageHubSetAllowFriendGroupsRequest) Reset() {
	*x = MessageHubSetAllowFriendGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubSetAllowFriendGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubSetAllowFriendGroupsRequest) ProtoMessage() {}

func (x *MessageHubSetAllowFriendGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubSetAllowFriendGroupsRequest.ProtoReflect.Descriptor instead.
func (*MessageHubSetAllowFriendGroupsRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{11}
}

func (x *MessageHubSetAllowFriendGroupsRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *MessageHubSetAllowFriendGroupsRequest) GetAllowFriendGroups() bool {
	if x != nil {
		return x.AllowFriendGroups
	}
	return false
}

type MessageHubSetExpirationDaysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubId          string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	ExpirationDays int32  `protobuf:"varint,2,opt,name=expiration_days,json=expirationDays,proto3" json:"expiration_days,omitempty"`
}

func (x *MessageHubSetExpirationDaysRequest) Reset() {
	*x = MessageHubSetExpirationDaysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubSetExpirationDaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubSetExpirationDaysRequest) ProtoMessage() {}

func (x *MessageHubSetExpirationDaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubSetExpirationDaysRequest.ProtoReflect.Descriptor instead.
func (*MessageHubSetExpirationDaysRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{12}
}

func (x *MessageHubSetExpirationDaysRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *MessageHubSetExpirationDaysRequest) GetExpirationDays() int32 {
	if x != nil {
		return x.ExpirationDays
	}
	return 0
}

type MessageHubReportMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubId    string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	ReportId string `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
}

func (x *MessageHubReportMessageRequest) Reset() {
	*x = MessageHubReportMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubReportMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubReportMessageRequest) ProtoMessage() {}

func (x *MessageHubReportMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubReportMessageRequest.ProtoReflect.Descriptor instead.
func (*MessageHubReportMessageRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{13}
}

func (x *MessageHubReportMessageRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *MessageHubReportMessageRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type MessageHubBlockUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubId  string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *MessageHubBlockUserRequest) Reset() {
	*x = MessageHubBlockUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubBlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubBlockUserRequest) ProtoMessage() {}

func (x *MessageHubBlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubBlockUserRequest.ProtoReflect.Descriptor instead.
func (*MessageHubBlockUserRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{14}
}

func (x *MessageHubBlockUserRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *MessageHubBlockUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_messagehub_proto protoreflect.FileDescriptor

var file_messagehub_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x17, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x75, 0x62, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x62, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x75,
	0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x75,
	0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x33, 0x0a, 0x15, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x19, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x6f, 0x73, 0x74, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0xd7, 0x02, 0x0a, 0x19,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x48, 0x75, 0x62, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x75, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x2e, 0x0a, 0x13,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x27, 0x0a, 0x0f,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x61, 0x79, 0x73, 0x22, 0x4c, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x75, 0x62, 0x48, 0x75, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x32, 0x0a, 0x04, 0x68, 0x75, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x48, 0x75,
	0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x75, 0x62, 0x52, 0x04, 0x68,
	0x75, 0x62, 0x73, 0x22, 0x30, 0x0a, 0x17, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75,
	0x62, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15,
	0x0a, 0x06, 0x68, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x68, 0x75, 0x62, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x18, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x75, 0x62, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x31, 0x0a, 0x18, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x75, 0x62, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x75, 0x62, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x19, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4e, 0x0a,
	0x17, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x75, 0x62, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x75, 0x62, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x36, 0x0a,
	0x18, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x55, 0x0a, 0x1d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x75, 0x62, 0x53, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x75, 0x62, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x75, 0x62, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x6e, 0x0a, 0x25,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x6f, 0x77, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x75, 0x62, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x64, 0x0a, 0x22,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x53, 0x65, 0x74, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x68, 0x75, 0x62, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61,
	0x79, 0x73, 0x22, 0x54, 0x0a, 0x1e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x75, 0x62, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x1a, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x75, 0x62, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x75, 0x62, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0xde, 0x05, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x75, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x36, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2f, 0x0a, 0x04, 0x48, 0x75, 0x62, 0x73,
	0x12, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x48, 0x75, 0x62,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x06, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x12, 0x1c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x48, 0x75, 0x62, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x75, 0x62, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x48, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x12, 0x1d, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x41, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x06, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x12, 0x1c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x75, 0x62, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x75, 0x62, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x22, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x75, 0x62, 0x53, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x4e, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x2a, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x6f, 0x77, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x48, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x12, 0x27, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x53, 0x65, 0x74, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x40, 0x0a, 0x0d, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x38, 0x0a,
	0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2e, 0x2f, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messagehub_proto_rawDescOnce sync.Once
	file_messagehub_proto_rawDescData = file_messagehub_proto_rawDesc
)

func file_messagehub_proto_rawDescGZIP() []byte {
	file_messagehub_proto_rawDescOnce.Do(func() {
		file_messagehub_proto_rawDescData = protoimpl.X.CompressGZIP(file_messagehub_proto_rawDescData)
	})
	return file_messagehub_proto_rawDescData
}

var file_messagehub_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_messagehub_proto_goTypes = []interface{}{
	(*MessageHubCreateRequest)(nil),               // 0: rpc.MessageHubCreateRequest
	(*MessageHubRegisterRequest)(nil),             // 1: rpc.MessageHubRegisterRequest
	(*MessageHubHubsResponseHub)(nil),             // 2: rpc.MessageHubHubsResponseHub
	(*MessageHubHubsResponse)(nil),                // 3: rpc.MessageHubHubsResponse
	(*MessageHubVerifyRequest)(nil),               // 4: rpc.MessageHubVerifyRequest
	(*MessageHubVerifyResponse)(nil),              // 5: rpc.MessageHubVerifyResponse
	(*MessageHubApproveRequest)(nil),              // 6: rpc.MessageHubApproveRequest
	(*MessageHubApproveResponse)(nil),             // 7: rpc.MessageHubApproveResponse
	(*MessageHubRemoveRequest)(nil),               // 8: rpc.MessageHubRemoveRequest
	(*MessageHubRemoveResponse)(nil),              // 9: rpc.MessageHubRemoveResponse
	(*MessageHubSetPostLimitRequest)(nil),         // 10: rpc.MessageHubSetPostLimitRequest
	(*MessageHubSetAllowFriendGroupsRequest)(nil), // 11: rpc.MessageHubSetAllowFriendGroupsRequest
	(*MessageHubSetExpirationDaysRequest)(nil),    // 12: rpc.MessageHubSetExpirationDaysRequest
	(*MessageHubReportMessageRequest)(nil),        // 13: rpc.MessageHubReportMessageRequest
	(*MessageHubBlockUserRequest)(nil),            // 14: rpc.MessageHubBlockUserRequest
	(*User)(nil),                                  // 15: rpc.User
	(*Empty)(nil),                                 // 16: rpc.Empty
}
var file_messagehub_proto_depIdxs = []int32{
	15, // 0: rpc.MessageHubHubsResponseHub.user:type_name -> rpc.User
	2,  // 1: rpc.MessageHubHubsResponse.hubs:type_name -> rpc.MessageHubHubsResponseHub
	0,  // 2: rpc.MessageHubService.Create:input_type -> rpc.MessageHubCreateRequest
	1,  // 3: rpc.MessageHubService.Register:input_type -> rpc.MessageHubRegisterRequest
	16, // 4: rpc.MessageHubService.Hubs:input_type -> rpc.Empty
	4,  // 5: rpc.MessageHubService.Verify:input_type -> rpc.MessageHubVerifyRequest
	6,  // 6: rpc.MessageHubService.Approve:input_type -> rpc.MessageHubApproveRequest
	8,  // 7: rpc.MessageHubService.Remove:input_type -> rpc.MessageHubRemoveRequest
	10, // 8: rpc.MessageHubService.SetPostLimit:input_type -> rpc.MessageHubSetPostLimitRequest
	11, // 9: rpc.MessageHubService.SetAllowFriendGroups:input_type -> rpc.MessageHubSetAllowFriendGroupsRequest
	12, // 10: rpc.MessageHubService.SetExpirationDays:input_type -> rpc.MessageHubSetExpirationDaysRequest
	13, // 11: rpc.MessageHubService.ReportMessage:input_type -> rpc.MessageHubReportMessageRequest
	14, // 12: rpc.MessageHubService.BlockUser:input_type -> rpc.MessageHubBlockUserRequest
	16, // 13: rpc.MessageHubService.Create:output_type -> rpc.Empty
	16, // 14: rpc.MessageHubService.Register:output_type -> rpc.Empty
	3,  // 15: rpc.MessageHubService.Hubs:output_type -> rpc.MessageHubHubsResponse
	5,  // 16: rpc.MessageHubService.Verify:output_type -> rpc.MessageHubVerifyResponse
	7,  // 17: rpc.MessageHubService.Approve:output_type -> rpc.MessageHubApproveResponse
	9,  // 18: rpc.MessageHubService.Remove:output_type -> rpc.MessageHubRemoveResponse
	16, // 19: rpc.MessageHubService.SetPostLimit:output_type -> rpc.Empty
	16, // 20: rpc.MessageHubService.SetAllowFriendGroups:output_type -> rpc.Empty
	16, // 21: rpc.MessageHubService.SetExpirationDays:output_type -> rpc.Empty
	16, // 22: rpc.MessageHubService.ReportMessage:output_type -> rpc.Empty
	16, // 23: rpc.MessageHubService.BlockUser:output_type -> rpc.Empty
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_messagehub_proto_init() }
func file_messagehub_proto_init() {
	if File_messagehub_proto != nil {
		return
	}
	file_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_messagehub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubHubsResponseHub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubHubsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubVerifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubVerifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubApproveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubApproveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubRemoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubSetPostLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubSetAllowFriendGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubSetExpirationDaysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubReportMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubBlockUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messagehub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messagehub_proto_goTypes,
		DependencyIndexes: file_messagehub_proto_depIdxs,
		MessageInfos:      file_messagehub_proto_msgTypes,
	}.Build()
	File_messagehub_proto = out.File
	file_messagehub_proto_rawDesc = nil
	file_messagehub_proto_goTypes = nil
	file_messagehub_proto_depIdxs = nil
}
