// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: messagehub.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MessageHubRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Details   string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	PostLimit int32  `protobuf:"varint,3,opt,name=post_limit,json=postLimit,proto3" json:"post_limit,omitempty"`
}

func (x *MessageHubRegisterRequest) Reset() {
	*x = MessageHubRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubRegisterRequest) ProtoMessage() {}

func (x *MessageHubRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubRegisterRequest.ProtoReflect.Descriptor instead.
func (*MessageHubRegisterRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHubRegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MessageHubRegisterRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *MessageHubRegisterRequest) GetPostLimit() int32 {
	if x != nil {
		return x.PostLimit
	}
	return 0
}

type MessageHubHubsResponseHub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address    string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	User       *User  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	CreatedAt  string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ApprovedAt string `protobuf:"bytes,5,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	DisabledAt string `protobuf:"bytes,6,opt,name=disabled_at,json=disabledAt,proto3" json:"disabled_at,omitempty"`
	Details    string `protobuf:"bytes,7,opt,name=details,proto3" json:"details,omitempty"`
	PostLimit  int32  `protobuf:"varint,8,opt,name=post_limit,json=postLimit,proto3" json:"post_limit,omitempty"`
}

func (x *MessageHubHubsResponseHub) Reset() {
	*x = MessageHubHubsResponseHub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubHubsResponseHub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubHubsResponseHub) ProtoMessage() {}

func (x *MessageHubHubsResponseHub) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubHubsResponseHub.ProtoReflect.Descriptor instead.
func (*MessageHubHubsResponseHub) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{1}
}

func (x *MessageHubHubsResponseHub) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageHubHubsResponseHub) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MessageHubHubsResponseHub) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *MessageHubHubsResponseHub) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MessageHubHubsResponseHub) GetApprovedAt() string {
	if x != nil {
		return x.ApprovedAt
	}
	return ""
}

func (x *MessageHubHubsResponseHub) GetDisabledAt() string {
	if x != nil {
		return x.DisabledAt
	}
	return ""
}

func (x *MessageHubHubsResponseHub) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *MessageHubHubsResponseHub) GetPostLimit() int32 {
	if x != nil {
		return x.PostLimit
	}
	return 0
}

type MessageHubHubsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hubs []*MessageHubHubsResponseHub `protobuf:"bytes,1,rep,name=hubs,proto3" json:"hubs,omitempty"`
}

func (x *MessageHubHubsResponse) Reset() {
	*x = MessageHubHubsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubHubsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubHubsResponse) ProtoMessage() {}

func (x *MessageHubHubsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubHubsResponse.ProtoReflect.Descriptor instead.
func (*MessageHubHubsResponse) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{2}
}

func (x *MessageHubHubsResponse) GetHubs() []*MessageHubHubsResponseHub {
	if x != nil {
		return x.Hubs
	}
	return nil
}

type MessageHubApproveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubId string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
}

func (x *MessageHubApproveRequest) Reset() {
	*x = MessageHubApproveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubApproveRequest) ProtoMessage() {}

func (x *MessageHubApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubApproveRequest.ProtoReflect.Descriptor instead.
func (*MessageHubApproveRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{3}
}

func (x *MessageHubApproveRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

type MessageHubRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubId string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
}

func (x *MessageHubRemoveRequest) Reset() {
	*x = MessageHubRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubRemoveRequest) ProtoMessage() {}

func (x *MessageHubRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubRemoveRequest.ProtoReflect.Descriptor instead.
func (*MessageHubRemoveRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{4}
}

func (x *MessageHubRemoveRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

type MessageHubSetPostLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubId     string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	PostLimit int32  `protobuf:"varint,2,opt,name=post_limit,json=postLimit,proto3" json:"post_limit,omitempty"`
}

func (x *MessageHubSetPostLimitRequest) Reset() {
	*x = MessageHubSetPostLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messagehub_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHubSetPostLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHubSetPostLimitRequest) ProtoMessage() {}

func (x *MessageHubSetPostLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagehub_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHubSetPostLimitRequest.ProtoReflect.Descriptor instead.
func (*MessageHubSetPostLimitRequest) Descriptor() ([]byte, []int) {
	return file_messagehub_proto_rawDescGZIP(), []int{5}
}

func (x *MessageHubSetPostLimitRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *MessageHubSetPostLimitRequest) GetPostLimit() int32 {
	if x != nil {
		return x.PostLimit
	}
	return 0
}

var File_messagehub_proto protoreflect.FileDescriptor

var file_messagehub_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x19, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x75, 0x62, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0xfe, 0x01, 0x0a, 0x19, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x75, 0x62, 0x48, 0x75, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x75, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x4c, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x75, 0x62, 0x48, 0x75, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x32, 0x0a, 0x04, 0x68, 0x75, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x48, 0x75,
	0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x75, 0x62, 0x52, 0x04, 0x68,
	0x75, 0x62, 0x73, 0x22, 0x31, 0x0a, 0x18, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75,
	0x62, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x15, 0x0a, 0x06, 0x68, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x68, 0x75, 0x62, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x17, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x48, 0x75, 0x62, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x68, 0x75, 0x62, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x1d, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x53, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x75, 0x62,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x75, 0x62, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x32,
	0xa6, 0x02, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x1e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x75, 0x62, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2f, 0x0a,
	0x04, 0x48, 0x75, 0x62, 0x73, 0x12, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x1b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x75, 0x62, 0x48, 0x75, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x07, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x12, 0x1d, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x32, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x1c,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3e, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x50,
	0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x22, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x75, 0x62, 0x53, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2e, 0x2f, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messagehub_proto_rawDescOnce sync.Once
	file_messagehub_proto_rawDescData = file_messagehub_proto_rawDesc
)

func file_messagehub_proto_rawDescGZIP() []byte {
	file_messagehub_proto_rawDescOnce.Do(func() {
		file_messagehub_proto_rawDescData = protoimpl.X.CompressGZIP(file_messagehub_proto_rawDescData)
	})
	return file_messagehub_proto_rawDescData
}

var file_messagehub_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_messagehub_proto_goTypes = []interface{}{
	(*MessageHubRegisterRequest)(nil),     // 0: rpc.MessageHubRegisterRequest
	(*MessageHubHubsResponseHub)(nil),     // 1: rpc.MessageHubHubsResponseHub
	(*MessageHubHubsResponse)(nil),        // 2: rpc.MessageHubHubsResponse
	(*MessageHubApproveRequest)(nil),      // 3: rpc.MessageHubApproveRequest
	(*MessageHubRemoveRequest)(nil),       // 4: rpc.MessageHubRemoveRequest
	(*MessageHubSetPostLimitRequest)(nil), // 5: rpc.MessageHubSetPostLimitRequest
	(*User)(nil),                          // 6: rpc.User
	(*Empty)(nil),                         // 7: rpc.Empty
}
var file_messagehub_proto_depIdxs = []int32{
	6, // 0: rpc.MessageHubHubsResponseHub.user:type_name -> rpc.User
	1, // 1: rpc.MessageHubHubsResponse.hubs:type_name -> rpc.MessageHubHubsResponseHub
	0, // 2: rpc.MessageHubService.Register:input_type -> rpc.MessageHubRegisterRequest
	7, // 3: rpc.MessageHubService.Hubs:input_type -> rpc.Empty
	3, // 4: rpc.MessageHubService.Approve:input_type -> rpc.MessageHubApproveRequest
	4, // 5: rpc.MessageHubService.Remove:input_type -> rpc.MessageHubRemoveRequest
	5, // 6: rpc.MessageHubService.SetPostLimit:input_type -> rpc.MessageHubSetPostLimitRequest
	7, // 7: rpc.MessageHubService.Register:output_type -> rpc.Empty
	2, // 8: rpc.MessageHubService.Hubs:output_type -> rpc.MessageHubHubsResponse
	7, // 9: rpc.MessageHubService.Approve:output_type -> rpc.Empty
	7, // 10: rpc.MessageHubService.Remove:output_type -> rpc.Empty
	7, // 11: rpc.MessageHubService.SetPostLimit:output_type -> rpc.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_messagehub_proto_init() }
func file_messagehub_proto_init() {
	if File_messagehub_proto != nil {
		return
	}
	file_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_messagehub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubHubsResponseHub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubHubsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubApproveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messagehub_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHubSetPostLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messagehub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messagehub_proto_goTypes,
		DependencyIndexes: file_messagehub_proto_depIdxs,
		MessageInfos:      file_messagehub_proto_msgTypes,
	}.Build()
	File_messagehub_proto = out.File
	file_messagehub_proto_rawDesc = nil
	file_messagehub_proto_goTypes = nil
	file_messagehub_proto_depIdxs = nil
}
